<?= $this->render('header.phtml'); ?>
    <table border="1">
        <tr>
            <th>Id</th>
            <th>Image</th>
            <th>Title</th>
            <th>Description</th>
            <th>Price</th>
            <th></th>

        </tr>
        <? foreach ($this->products as $product): ?>
            <tr>
                <td><?= $product->productId ?></td>
                <td><img src="images/<?= $product->productImg ?>" style="width:250px; height:250px;"/></td>
                <td><?= $product->productTitle ?></td>
                <td><?= $product->productDesc ?></td>
                <td><?= $product->productPrice ?></td>
                <td><a href="/index/removefromcart/id/<?= $product->productId ?>">Remove from cart</a></td>

            </tr>
        <? endforeach; ?>
    </table>
<?= $this->render('footer.phtml'); ?>