<?= $this->render('header.phtml'); ?>
<? if(strcmp($this->emptycart, 'Cart is empty')==0): ?>
    <h1>Your cart is empty</h1>
    <?= 'To add products in the cart please return to the store' ?>
    </br>
    <a href="/index">Return to the store</a>
    <? else: ?>
    <table border="1">
        <tr>
            <th>Id</th>
            <th>Image</th>
            <th>Title</th>
            <th>Description</th>
            <th>Price</th>
            <th></th>

        </tr>
        <? foreach ($this->products as $product): ?>
            <tr>
                <td><?= $product->productId ?></td>
                <td><img src="/images/<?= $product->productImg ?>" style="width:250px; height:250px;"/></td>
                <td><?= $product->productTitle ?></td>
                <td><?= $product->productDesc ?></td>
                <td><?= $product->productPrice ?></td>
                <td><a href="/index/removefromcart/id/<?= $product->productId ?>">Remove from cart</a></td>

            </tr>
        <? endforeach; ?>
    </table>
    <? endif; ?>
<? print_r($this->prids) ?>
<?= $this->render('footer.phtml'); ?>