<?= $this->render('header.phtml'); ?>
    <div id="navbar">
        <ul id="navbar-list">
            <li><a href="/index/cart">Cart</a></li>
            <li><a href="/index">Products</a></li>
        </ul>
    </div>
    <table>
        <tr>
            <th>Id</th>
            <th>Image</th>
            <th>Title</th>
            <th>Description</th>
            <th>Price</th>
            <th></th>
                
        </tr>                                      
        <? foreach ($this->products as $product): ?>
            <tr>
                <td><?= $product->productId ?></td>
                <td><img src="images/<?= $product->productImg ?>" style="width:250px; height:250px;"/></td>
                <td><?= $product->productTitle ?></td>
                <td><?= $product->productDesc ?></td>
                <td><?= $product->productPrice ?></td>
                <td><a href="/index/addtocart/id/<?= $product->productId ?>">Add to cart</a></td>
            </tr>                                      
        <? endforeach; ?>
    </table>
    <br />
<?= $this->render('footer.phtml'); ?>