<?= $this->render('header.phtml'); ?>
    <table border="1">
        <tr>
            <th>Id</th>
            <th>Image</th>
            <th>Title</th>
            <th>Description</th>
            <th>Price</th>
            <th></th>
        </tr>                                      
        <? foreach ($this->products as $product): ?>
            <tr>
                <td><?= $product->productId ?></td>
                <td><?= $product->productImg ?></td>
                <td><?= $product->productTitle ?></td>
                <td><?= $product->productDesc ?></td>
                <td><?= $product->productPrice ?></td>
            </tr>                                      
        <? endforeach; ?>
    </table>
    <br />
    <a href="/index/adauga">Adauga</a>
<?= $this->render('footer.phtml'); ?>